### PR TITLE
Rename nhg/partial to nhg/thunk

### PR DESCRIPTION
**Pull request by ajoslin**
A Thunk is a core programming concept, one very separate from that of partial application.

Thunks have to do with optimization, partial application has to do with .. partial application.

### CODE REVIEW

**Comment by chrisinajar** [comment]
Hmm, interesting. I honestly haven't used it, I just built the initial API set purely on the non-depreciated entries in `mercury`. I agree that the name isn't entirely accurate, and perhaps one could even propose a `partial` API to take it's place.

This is the relevant line in mercury: https://github.com/Raynos/mercury/blob/master/index.js#L58

**Comment by ajoslin** [comment]
I just know that this is confusing:

```
var partial = require('ap').partial
var Thunk = require('nhg/partial')
```

Thunk is used as an optimization to only re-render when something has explicitly changed. I think the name `thunk` just makes sense. See [vdom-thunk's readme](https://github.com/Raynos/vdom-thunk#example).

**Comment by chrisinajar** [comment]
directly from their readme, first thing written there

```
Use partial when you want to avoid re-rendering subtrees.

partial will only re-evaluate the subtree if the arguments you pass to it change. This means you should use an immutable data structure (like observ-struct)

var partial = require("vdom-thunk")
```

https://www.npmjs.com/package/vdom-thunk

Hmm, looks like the master repo calls it thunk though... weird. Perhaps raynos started renaming it from partial to thunk and didn't follow through?

**Comment by ajoslin** [comment]
Looks like he renamed it from partial to thunk in the readme but didn't publish the readme edits.

**Pull request merged**
